name: taxiye_passenger
description: Taxiye Passenger flutter app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # For state, route Management
  get: ^4.3.8
  # For key value storage, like sharedprefernce.
  get_storage: ^2.0.3
  # For network requests
  dio: ^4.0.0


  # For immutability classes, jason parser 
  freezed_annotation: ^0.14.2
  # for # date formatting and others 
  intl: ^0.17.0
  # For file picking
  # file_picker: ^3.0.3

  
  # For image picking
  image_picker: ^0.8.4+3
  # For caching images
  cached_network_image: ^3.1.0
  # For sharing 
  share: ^2.0.4
  

  # For smooth dot page indicator 
  smooth_page_indicator: ^0.3.0-nullsafety.0
  # For OTP pin input 
  pinput: ^1.2.0
  # for image cropper
  image_cropper: ^1.4.1

   # firebase services 
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9


  # For google maps 
  google_maps_flutter: ^2.0.11
  # For drawing polylines
  flutter_polyline_points: ^1.0.0
  # For svg images
  flutter_svg: ^0.22.0
  # For star rating
  flutter_rating_bar: ^4.0.0


  # For getting unique device ids
  # device_info: ^2.0.2
  device_info_plus: ^3.1.0
  # For getting package info
  # package_info: ^2.0.2
  package_info_plus: ^1.3.0
  # For getting location
  geolocator: ^7.7.1
  # For getting location names 
  geocoding: ^2.0.1


  # progress hud with null safety support
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # For hasshing values 
  crypto: ^3.0.1

  # Social logins 
  # For firebase auth 
  firebase_auth: ^3.1.4
  # For google sign in
  google_sign_in: ^5.2.0
  # For facebook sign in 
  flutter_facebook_auth: ^3.5.1
  # For apple sign in
  sign_in_with_apple: ^3.0.0
  # For twitter sign in
  twitter_login: ^4.0.1


  # For pulse animation marker
  flutter_animarker: ^3.2.0
  # For generating unique ids
  uuid: ^3.0.4
  # For storing environment variables
  flutter_dotenv: ^5.0.2
  # for showing local notifications
  flutter_local_notifications: ^8.2.0

  # for a spin kit 
  flutter_spinkit: ^5.1.0
  # for local storage
  shared_preferences: ^2.0.8
  # for launching a URL
  url_launcher: ^6.0.12

  # for picking contacts
  contacts_service: ^0.6.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^0.14.2
  json_serializable: ^4.1.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/map/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. 
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 600
    - family: SegoeUi
      fonts:
        - asset: assets/fonts/SegoeUI-Regular.ttf
          weight: 400
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
